### ISSUE TITLE
Examples are broken: after logging in, still unauthorized.

### ISSUE THREAD

**Issue by ddellacosta** [ddellacosta/friend-oauth2-examples#4]
Can't get anything but "sorry, you don't have access..."  Hmm.

**Comment by rockBreaker** [comment]
Any chance of merging that pull request? I'm having trouble getting the demo to work even with that merge locally.

**Comment by rockBreaker** [comment]
This PR fixed all my issues.

https://github.com/ddellacosta/friend-oauth2-examples/commit/f5129b1cd5371173a0ddb1963b8f7cfcc88ffdf1
